### ISSUE TITLE
[BUG]: Some Icons not support such as <IconOutline name="x-mark-outline" />

### ISSUE THREAD

**Issue by fanshuai** [shinokada/svelte-heros#10]
### Description of the bug

npm run dev error log info:

```
TypeError: Cannot read properties of undefined (reading 'box')
    at IconOutline.svelte:34:26
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at eval (/src/routes/+page.svelte:15:94)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at Object.default (root.svelte:42:40)
    at eval (/src/routes/+layout.svelte:11:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at root.svelte:41:39
    at $$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:2005:26)
```

### Steps To Reproduce

1. Open Browser with url `https://stackblitz.com/edit/daisyui-sveltekit/`
2. Terminal: `npm i svelte-heros@4.2.0 -D`
3. edit `src/routes/+page.svelte` with:
```
<button class="btn">Hello daisyUI</button>
<IconSolid name="academic-cap-solid" />
<IconOutline name="academic-cap-outline" />
<IconSolid name="x-circle-solid" />
<IconOutline name="x-mark-outline" />
<script>
  import { IconSolid, IconOutline } from 'svelte-heros';
</script>
```
4. Terminal: `npm run dev`

**Comment by shinokada** [comment]
`<IconOutline name="x-mark-outline" />` should be `<IconOutline name="x-circle-outline" />`.

Please check the names at https://svelte-heros.vercel.app/outline.
